#!/bin/sh

docker stop devbasecontainer
docker run -d --rm -p 22001:22 \
	--mount type=bind,src=$HOME/dotfiles,dst=/home/dev/dotfiles,consistency=delegated \
	--mount type=bind,src=$HOME/work,dst=/home/dev/work,consistency=delegated \
	--name devcontainer \
	dev
