#!/bin/sh

docker stop devbasecontainer
docker run -d --rm \
	-p 22001:22 -p 1234:1234 -p 8080:8080 -p 8081:8081 -p 8082:8082 -p 6060:6060 \
	--mount type=bind,src=$HOME/dotfiles,dst=/home/dev/dotfiles,consistency=delegated \
	--mount type=bind,src=$HOME/ghq,dst=/home/dev/ghq,consistency=delegated \
	--mount type=bind,src=$HOME,dst=/x,consistency=delegated \
	--name devcontainer \
	dev
