#!/bin/sh
# shell共通設定

# PATH
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:~/go/bin

if type rbenv > /dev/null 2>&1
then
	eval "$(rbenv init -)"
fi

# ENV
export TERM=xterm-256color
export EDITOR=vim

# aliases
alias e='vim'
alias d='docker'
alias dc='docker-compose'
alias n='fg'
alias m='make'
alias g='lazygit'
alias gs='git status'
alias i='git status -sb'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gdd="git diff --color-words --word-diff-regex='\\w+|[^[:space:]]'"
alias gf='git fetch -p'
alias gm='git merge --no-ff'
alias gk='git checkout'
alias gp='git pull -p'
alias gl='git log'
alias gb='git branch'
alias catj='iconv -f cp932 -t utf8'
alias q,="q -H -d,"
alias sc='systemctl'
alias ssc='sudo systemctl'

# alias devbase='ssh -A dev@localhost -p 22000'
# alias dev='ssh -A dev@localhost -p 22001'

# scripts
case "${OSTYPE}" in
	darwin*)
		alias ls="ls -G"
		alias l_zqx="ls -alG"

		alias tac="tail -r"
		;;
	linux*)
		alias ls="ls --color"
		alias l_zqx="ls -al --color"
		;;
esac

jr () {
	local repo=$(ghq list | gof -f)
	if [ -n "$repo" ]; then
		repo=$(ghq list --full-path --exact $repo)
		cd ${repo}
	fi
}


[ -f ~/.anyshrc.local ] && source ~/.anyshrc.local
