set runtimepath+=$HOME

syntax on

" basic settings
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,cp932,euc-jp

set nobackup
set noswapfile

set autoread
set autowrite
set backupcopy=yes

set showcmd
set showmatch
set matchtime=1

set tabstop=2
set shiftwidth=2

set hlsearch
set ignorecase
set smartcase
set smartindent

set scrolloff=10

set backspace=eol,indent,start

set updatetime=300

set title

noremap h h
noremap t j
noremap r k
noremap s l

nnoremap e v
nnoremap n V
nnoremap E <C-v>

noremap l f
noremap L F

noremap ( N
noremap ) n

map Y y$
noremap m <C-o>
noremap M <C-i>

nnoremap + <C-a>
nnoremap - <C-x>

noremap <BS> "_xh
noremap x "_s

" quick mark
noremap H mH
noremap kh `H

nnoremap <C-p> :cprevious<CR>
nnoremap <C-n> :cnext<CR>
nnoremap <C-q> :cclose<CR>
nnoremap <C-l> zt

" navigate windows
nnoremap <Left>  <C-w>h
nnoremap <Down>  <C-w>j
nnoremap <Up>    <C-w>k
nnoremap <Right> <C-w>l

" save
nnoremap j :w<CR>

if isdirectory(expand('~/.vim'))
	runtime! .vim/min/**/*.vim

	" load advanced settings
	if v:version >= 800
		if has('win32')
			source ~/.vim/autoload/plug.vim
		endif
		source ~/.vim/plugins.vim
		runtime! .vim/full/**/*.vim
		runtime! .vim/plug/**/*.vim
	endif

	if has('win32')
		set runtimepath+=$HOME/.vim/after
	endif
endif
