---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/dotfiles/settings/anyshrc", dest: "~/.anyshrc"}
    - { src: "~/dotfiles/settings/bashrc", dest: "~/.bashrc"}
    - { src: "~/dotfiles/settings/sshrc", dest: "~/.sshrc"}
    - { src: "~/dotfiles/settings/vimrc", dest: "~/.vimrc"}
    - { src: "~/dotfiles/settings/zshrc", dest: "~/.zshrc"}
    - { src: "~/dotfiles/settings/gitconfig_shared", dest: "~/.gitconfig_shared"}
    - { src: "~/dotfiles/settings/gitignore_global", dest: "~/.gitignore_global"}
    - { src: "~/dotfiles/settings/vim/advanced", dest: "~/.vim/advanced"}
    - { src: "~/dotfiles/settings/vim/after", dest: "~/.vim/after"}
    - { src: "~/dotfiles/settings/vim/basic", dest: "~/.vim/basic"}
    - { src: "~/dotfiles/settings/vim/plug", dest: "~/.vim/plug"}
    - { src: "~/dotfiles/settings/sshrc.d", dest: "~/.sshrc.d"}

    - { src: "~/ghq/github.com/junegunn/vim-plug/plug.vim", dest: "~/.vim/autoload/plug.vim" }
