---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/dotfiles/home/bashrc", dest: "~/.bashrc"}
    - { src: "~/dotfiles/home/vimrc", dest: "~/.vimrc"}
    - { src: "~/ghq/github.com/junegunn/vim-plug/plug.vim", dest: "~/.vim/autoload/plug.vim" }
    - { src: "~/ghq/github.com/junegunn/fzf", dest: "~/.fzf" }
