---
- name: include brew formula list
  include_vars: vars/formula.yml
  tags:
    - brew_formula

- name: include pacman list
  include_vars: vars/pacman.yml
  tags:
    - pacman

- block:
  - name: manage formula
    homebrew:
      name: "{{ item.key }}"
      state: present
    with_dict: "{{ formula }}"
    tags:
      - brew_formula

  when: ansible_os_family == "Darwin"

- block:
  - name: manage pacman
    become: yes
    ignore_errors: true
    pacman:
      name: "{{ item.key }}"
      state: present
    with_dict: "{{ pacman }}"

  when: ansible_os_family == "Archlinux"

- name: check gopls
  command: which gopls
  register: gopls_exists
  ignore_errors: true

- name: install gopls
  shell: cd /tmp; go get -u golang.org/x/tools/cmd/gopls
  when: gopls_exists is failed

- name: check goimports
  command: which goimports
  register: goimports_exists
  ignore_errors: true

- name: install goimports
  shell: cd /tmp; go get -u golang.org/x/tools/cmd/goimports
  when: goimports_exists is failed


