#!/bin/sh

mkdir -p ~/.cache/vim

if [ ! -e "$HOME"/.fzf/bin ]; then
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install
fi

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

git config --global --replace-all ghq.root $HOME/.ghq
git config --global --add ghq.root $HOME/go/src

# only post rcup
if [ -e "$HOME"/.rcrc ]; then
	git config --global user.name "eihigh"
	git config --global user.email "eihigh.contact@gmail.com"

	ln -sf $HOME/dotfiles/.sshrc.d ~/
fi
