#!/bin/sh

go get -u -v github.com/motemen/ghq
go get -u -v golang.org/x/tools/cmd/gopls
go get -u -v github.com/jesseduffield/lazygit
go get -u -v github.com/monochromegane/the_platinum_searcher/...
